### ISSUE TITLE
Dotenv not working

### ISSUE THREAD

**Issue by mahdiyari** [Savory/Danet-Starter#7]
Latest Deno version

```
danet new testapi // select postgres
cd testapi
nano .env // add env varibales
deno task launch-server
// postgres error because env variables are not loaded
```
I did `console.log(Deno.env.toObject())` at `postgres.serivce.ts` and env variables are not present.

**Comment by isaactzab** [comment]
isaactzab:jsrI suggest update bootstrap where dotenv is imported from import '@std/dotenv'; to import "jsr:@std/dotenv/load";. This has been work for me.

**Comment by Sorikairox** [comment]
@isaactzab thank you for opening this issue. I made the JSR version the main branch, and applied a fix so it shouldn't happen again !
